[package]
name = "job_system"
version = "0.1.0"
authors = ["Squares <m.piotr@moscicki.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"